### ISSUE TITLE
Main function is not generated

### ISSUE THREAD

**Issue by urosjarc** [fusionlanguage/fut#73] opened 2022-09-25 22:54 UTC
For the following languages, main function does not exists: c, cpp, python, js, ts.
For python the docs are correct.

## SOURCE
```
public class MainP {

    public static void Main(string[] args)
    {
    }

}
```

## c
```
// Generated automatically with "cito". Do not edit.
#include <stdlib.h>
#include "MainP.h"

struct MainP {
};

void MainP_Main(const char *const *args)
{
}
```

## cpp
```
// Generated automatically with "cito". Do not edit.
#include "MainP.hpp"

void MainP::main(std::string_view const * args)
{
}
```

## js
Expected result should be to call MainP.main function after definition.
```
// Generated automatically with "cito". Do not edit.

"use strict";

function MainP()
{
}

MainP.main = function(args)
{
}

```

## python
Expected result should be
```
if __name__ == '__main__':
     MainP.main(sys.args)
```

```
# Generated automatically with "cito". Do not edit.

class MainP:

	@staticmethod
	def main(args):
		pass

```

## ts
Expected result should be the same as with js.
```
// Generated automatically with "cito". Do not edit.
export class MainP
{
	public static main(args: readonly (string | null)[] | null): void
	{
	}
}

```

**Comment by urosjarc** [comment] 2022-09-25 22:57
BTW do you guys trying to target vanilla js or node.js?

**Comment by pfusik** [comment] 2022-09-26 06:58
This is by design. Unlike other programming languages, Ć is _not_ meant for writing full programs, but only components/libraries easily usable from other programming languages. See [some projects in Ć](https://github.com/pfusik/cito/issues/21).

As for the other question, the goal is to target both. As of now there's just one built-in: `Environment.GetEnvironmentVariable` that only works with Node.js and not a browser.

**Comment by urosjarc** [comment] 2022-09-26 08:08
Cito to be recognized as an official language has to have a main function otherwise it's a joust library transpiler. Can you reopen this issue because I think it's an easy fix... check if the function signature matches the main function... Create some code in the output. Im considering to create pull request for this to fix it my self.

**Comment by pfusik** [comment] 2022-09-26 09:37
Yes, it's a library transpiler. Why bother with transpiling if you compile to an exe in the end?

**Comment by urosjarc** [comment] 2022-09-26 13:02
I don't understand your logic on why this feature is not necessary. I would like to create complete programs with cito not joust libraries to be used somewhere else.

**Comment by pfusik** [comment] 2022-09-26 13:22
I understand that you ask for is an ability to:

1. Write a program in Ć.
2. Transpile to e.g. C or C#.
3. Compile the C or C# code into an executable.

I would rather write the whole program in C or C# instead. I don't see how Ć would add any value as a transpiler to whole programs?

**Comment by urosjarc** [comment] 2022-09-26 14:28
I still don't understand your logic... In cito source file... If user writes main function why wouldn't cito create main function in transpiled output? If user doesn't write main function then cito will not create main function... I don't see what is the problem here?

**Comment by pfusik** [comment] 2022-09-26 19:33
Technically this should be rather easy. It could be very useful for people experimenting with Ć. I'll probably add it.

**Comment by pfusik** [comment] 2022-09-26 19:53
Also, it enables a simple testing system with no extra dependencies:

    public static class Foo
    {
        public static int Add(int x, int y) => x + y;
        public static void Main()
        {
            assert Add(1, 2) == 3;
            assert Add(5, 7) == 12;
        }
    }

**Comment by iahung2** [comment] 2023-09-27 12:10
> Technically this should be rather easy. It could be very useful for people experimenting with Ć. I'll probably add it.

What do you want to do now? Should this issue be closed? You closed my issue!

**Comment by pfusik** [comment] 2023-09-27 12:16
This is in queue. There are several tasks of higher priority.

**Comment by iahung2** [comment] 2023-09-27 12:23
> This is in queue. There are several tasks of higher priority.

Isn't the very trick you tell me could be used? So this is no longer a problem and you seem also not interested in finding a solution. As there is already workaround and adding support for `Main` function is a compromise on what Fusion was designed for in your opinion. Why don't you just close this as not planned the same way you closed my issue? The OP is gone. He said he will implement his own solution and he will not use Fusion (at the time still called Cito): https://github.com/fusionlanguage/fut/discussions/75#discussioncomment-3741233

**Closed** 2023-11-02 10:39 UTC
Labels: enhancement

**Comment by pfusik** [comment] 2023-11-02 10:41
This is implemented now. See [the documentation](https://github.com/fusionlanguage/fut/blob/master/doc/reference.md#main-method).
