### ISSUE TITLE
Correctly generate the main function for C/C++

### ISSUE THREAD

**Issue by iahung2** [fusionlanguage/fut#132] opened 2023-09-27 07:49 UTC
For example, this Fusion code correctly translated to C# and Java:

`public static void Main(string[] args)`

But it doesn't work for C/C++.

I tried a main function without parameters:

```
public class Test {
	public static void main() {
	}
}
```

It translated to `void Test_main(void)` in C and `void Test::main()` in C++.

I suggest treating the `Main` function as a special function if translating to target C/C++. It should be put outside of any classes or structs in the generated code.

I also suggest Fusion to correctly translate this `Main` function to C/C++:

`public static int Main(int argc, string[] argv)`

It should correctly translate to `int main(int argc, char *argv[])`.

Why I suggest using another `Main` function in Fusion code if translating to C/C++? Because this `Main` function will not correctly translate to C/C++:

`public static void Main(string[] args)`

It's more optimized for C# and Java.

Following this discipline, we will have to write two `Main` function. One is specific to C/C++. One is for the rest. Conditional compilation will help. This is acceptable IMO.

**Comment by pfusik** [comment] 2023-09-27 09:40
Duplicate of #73

**Closed by pfusik** 2023-09-27 09:40 UTC

**Comment by pfusik** [comment] 2023-09-27 11:30
Fusion is a language for authoring libraries, not command-line programs. Libraries do not have `main`. Why would you need `main` generated from your Fusion code?

There's a trivial workaround, simply link with this C code:
```c
#include "myfusionlib.h"

int main(int argc, char **argv)
{
    MyFusionClass_Main(argc, argv);
}
```
